/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check endpoint */
    get: operations["HealthController_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user [Public] */
    post: operations["AuthController_register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login user [Public] */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh access token [Public] */
    post: operations["AuthController_refreshToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user info [Any Role] */
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/users/{userId}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user role [Admin] */
    patch: operations["AuthController_updateUserRole"];
    trace?: never;
  };
  "/api/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all customers (admin only) */
    get: operations["CustomersController_findAll"];
    put?: never;
    /** Create a new customer (admin only) */
    post: operations["CustomersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current customer profile */
    get: operations["CustomersController_getMyProfile"];
    /** Update current customer profile */
    put: operations["CustomersController_updateMyProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get customer by ID (admin only) */
    get: operations["CustomersController_findById"];
    /** Update customer by ID (admin only) */
    put: operations["CustomersController_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/me/addresses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add new address to customer profile */
    post: operations["CustomersController_addAddress"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/me/addresses/{addressId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove address from customer profile */
    delete: operations["CustomersController_removeAddress"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/me/favorites/{restaurantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add restaurant to favorites */
    post: operations["CustomersController_addFavorite"];
    /** Remove restaurant from favorites */
    delete: operations["CustomersController_removeFavorite"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/me/favorites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all favorite restaurants */
    get: operations["CustomersController_getFavorites"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all active restaurants [Public] */
    get: operations["RestaurantsController_findAll"];
    put?: never;
    /** Create a new restaurant [Admin, Restaurant Owner] */
    post: operations["RestaurantsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all restaurants including inactive [Admin] */
    get: operations["RestaurantsController_findAllIncludingInactive"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get restaurant by ID [Public] */
    get: operations["RestaurantsController_findById"];
    /** Update restaurant [Admin, Restaurant Owner] */
    put: operations["RestaurantsController_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate restaurant [Admin, Restaurant Owner] */
    post: operations["RestaurantsController_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate restaurant [Admin, Restaurant Owner] */
    post: operations["RestaurantsController_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{restaurantId}/orders/{orderId}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm an order [Admin, Restaurant Owner] */
    post: operations["RestaurantsController_confirmOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{restaurantId}/orders/{orderId}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject an order [Admin, Restaurant Owner] */
    post: operations["RestaurantsController_rejectOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{restaurantId}/menu": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get menu items for a restaurant [Public] */
    get: operations["MenuItemsController_findByRestaurant"];
    put?: never;
    /** Create a new menu item [Admin, Restaurant Owner] */
    post: operations["MenuItemsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{restaurantId}/menu/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all menu items including unavailable [Admin, Restaurant Owner] */
    get: operations["MenuItemsController_findAllByRestaurant"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{restaurantId}/menu/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update menu item [Admin, Restaurant Owner] */
    put: operations["MenuItemsController_update"];
    post?: never;
    /** Delete menu item [Admin, Restaurant Owner] */
    delete: operations["MenuItemsController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/drivers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all drivers (admin only) */
    get: operations["DriversController_findAll"];
    put?: never;
    /** Create a new driver */
    post: operations["DriversController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/drivers/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available drivers */
    get: operations["DriversController_findAvailable"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/drivers/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current driver profile */
    get: operations["DriversController_getMyProfile"];
    /** Update current driver profile */
    put: operations["DriversController_updateMyProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/drivers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get driver by ID (admin only) */
    get: operations["DriversController_findById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/drivers/me/location": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update driver location */
    patch: operations["DriversController_updateLocation"];
    trace?: never;
  };
  "/api/drivers/me/availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set driver availability status */
    patch: operations["DriversController_setAvailability"];
    trace?: never;
  };
  "/api/drivers/me/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Deactivate current driver account */
    patch: operations["DriversController_deactivateMyAccount"];
    trace?: never;
  };
  "/api/drivers/{id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Deactivate a driver (admin only) */
    patch: operations["DriversController_deactivateDriver"];
    trace?: never;
  };
  "/api/cart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current customer cart [Customer] */
    get: operations["CartsController_getMyCart"];
    put?: never;
    post?: never;
    /** Clear cart [Customer] */
    delete: operations["CartsController_clearCart"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cart/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add item to cart [Customer] */
    post: operations["CartsController_addItem"];
    /** Remove item from cart [Customer] */
    delete: operations["CartsController_removeItem"];
    options?: never;
    head?: never;
    /** Update item quantity in cart [Customer] */
    patch: operations["CartsController_updateItemQuantity"];
    trace?: never;
  };
  "/api/cart/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Checkout cart and create order [Customer] */
    post: operations["CartsController_checkout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new order (customer) */
    post: operations["OrdersController_createOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/my-orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get customer orders */
    get: operations["OrdersController_getMyOrders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{id}/pay": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pay for an order (customer) */
    post: operations["OrdersController_payForOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available orders for drivers */
    get: operations["OrdersController_getAvailableOrders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/my-deliveries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get driver deliveries */
    get: operations["OrdersController_getMyDeliveries"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept an order (driver) */
    post: operations["OrdersController_acceptOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update order status */
    patch: operations["OrdersController_updateOrderStatus"];
    trace?: never;
  };
  "/api/orders/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel an order */
    post: operations["OrdersController_cancelOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get order by ID */
    get: operations["OrdersController_getOrderById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
      phone: string;
    };
    AuthResponseDto: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      accessToken: string;
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      refreshToken: string;
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    RefreshTokenDto: {
      refreshToken: string;
    };
    UserInfoResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      userId: string;
      /** @example user@example.com */
      email: string;
      /**
       * @example [
       *       "customer"
       *     ]
       */
      roles: string[];
    };
    UpdateUserRoleDto: {
      /** @enum {string} */
      role: "customer" | "driver" | "admin" | "restaurant_owner";
    };
    CustomerAddressDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example Home */
      label?: string;
      /** @example 123 Main Street */
      street: string;
      /** @example New York */
      city: string;
      /** @example 10001 */
      postalCode: string;
      /** @example USA */
      country: string;
      /** @example 40.7128 */
      latitude?: number;
      /** @example -74.006 */
      longitude?: number;
    };
    CustomerResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example customer@example.com */
      email: string;
      /** @example John Doe */
      name: string;
      /** @example +1-555-0101 */
      phone: string;
      addresses: components["schemas"]["CustomerAddressDto"][];
      /**
       * @example [
       *       "123e4567-e89b-12d3-a456-426614174001",
       *       "123e4567-e89b-12d3-a456-426614174002"
       *     ]
       */
      favoriteRestaurantIds: string[];
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    CreateCustomerDto: {
      /** Format: email */
      email: string;
      name: string;
      phone: string;
    };
    UpdateCustomerDto: {
      name: string;
      phone: string;
    };
    AddAddressDto: {
      address: {
        /** Format: uuid */
        id?: string;
        label?: string;
        street: string;
        city: string;
        postalCode: string;
        country: string;
        latitude?: number;
        longitude?: number;
      };
    };
    RestaurantAddressDto: {
      /** @example 123 Main Street */
      street: string;
      /** @example New York */
      city: string;
      /** @example NY */
      state?: string;
      /** @example 10001 */
      postalCode: string;
      /** @example USA */
      country: string;
      /** @example 40.7128 */
      latitude?: number;
      /** @example -74.006 */
      longitude?: number;
    };
    RestaurantResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      ownerId: string;
      /** @example Pizza Paradise */
      name: string;
      /** @example Authentic Italian pizza with fresh ingredients */
      description: string;
      address: components["schemas"]["RestaurantAddressDto"];
      /** @example +1-555-0101 */
      phone: string;
      /** @example contact@pizzaparadise.com */
      email: string;
      /** @example true */
      isActive: boolean;
      /**
       * @example {
       *       "monday": {
       *         "open": "09:00",
       *         "close": "22:00"
       *       },
       *       "tuesday": {
       *         "open": "09:00",
       *         "close": "22:00"
       *       }
       *     }
       */
      openingHours: {
        [key: string]: {
          /** @example 09:00 */
          open?: string;
          /** @example 22:00 */
          close?: string;
        };
      };
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    CreateRestaurantDto: {
      name: string;
      description: string;
      address: {
        street: string;
        city: string;
        postalCode: string;
        country: string;
        latitude?: number;
        longitude?: number;
      };
      phone: string;
      /** Format: email */
      email: string;
      /** @default {} */
      openingHours: {
        [key: string]: {
          open: string;
          close: string;
        };
      };
    };
    UpdateRestaurantDto: {
      name: string;
      description: string;
      address: {
        street: string;
        city: string;
        postalCode: string;
        country: string;
        latitude?: number;
        longitude?: number;
      };
      phone: string;
      /** Format: email */
      email: string;
      openingHours: {
        [key: string]: {
          open: string;
          close: string;
        };
      };
    };
    ConfirmOrderDto: {
      /** @default 30 */
      estimatedPreparationMinutes: number;
    };
    RejectOrderDto: {
      reason: string;
    };
    MenuItemResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      restaurantId: string;
      /** @example Margherita Pizza */
      name: string;
      /** @example Classic pizza with tomato, mozzarella, and basil */
      description: string;
      /** @example 12.99 */
      price: number;
      /** @example EUR */
      currency: string;
      /**
       * @example main_course
       * @enum {string}
       */
      category: "appetizer" | "main_course" | "dessert" | "beverage" | "side";
      /** @example https://example.com/images/pizza.jpg */
      imageUrl?: Record<string, never>;
      /** @example 15 */
      preparationTime: number;
      /** @example true */
      isAvailable: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    CreateMenuItemDto: {
      name: string;
      description: string;
      price: number;
      /** @default EUR */
      currency: string;
      /** @enum {string} */
      category: "appetizer" | "main_course" | "dessert" | "beverage" | "side";
      /** Format: uri */
      imageUrl?: string | null;
      /** @default 15 */
      preparationTime: number;
    };
    UpdateMenuItemDto: {
      name: string;
      description: string;
      price: number;
      currency: string;
      /** @enum {string} */
      category: "appetizer" | "main_course" | "dessert" | "beverage" | "side";
      /** Format: uri */
      imageUrl?: string | null;
      preparationTime: number;
      isAvailable: boolean;
    };
    DriverLocationDto: {
      /** @example 40.7128 */
      latitude: number;
      /** @example -74.006 */
      longitude: number;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    DriverResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      userId: string;
      /** @example Sedan */
      vehicleType: string;
      /** @example ABC-1234 */
      licensePlate: string;
      /**
       * @example available
       * @enum {string}
       */
      status: "available" | "busy" | "offline";
      currentLocation?: components["schemas"]["DriverLocationDto"];
      /** @example 4.8 */
      rating: number;
      /** @example 150 */
      totalDeliveries: number;
      /** @example true */
      isActive: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    CreateDriverDto: {
      vehicleType: string;
      licensePlate: string;
    };
    UpdateDriverDto: {
      vehicleType: string;
      licensePlate: string;
    };
    UpdateLocationDto: {
      latitude: number;
      longitude: number;
    };
    SetAvailabilityDto: {
      /** @enum {string} */
      status: "available" | "busy" | "offline";
    };
    CartItemDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      menuItemId: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      restaurantId: string;
      /** @example Margherita Pizza */
      name: string;
      /** @example 12.99 */
      price: number;
      /** @example EUR */
      currency: string;
      /** @example 2 */
      quantity: number;
    };
    CartResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      customerId: string;
      /** @example 123e4567-e89b-12d3-a456-426614174002 */
      restaurantId?: Record<string, never>;
      items: components["schemas"]["CartItemDto"][];
      /** @example 25.98 */
      totalAmount: number;
      /** @example EUR */
      currency: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    AddItemToCartDto: {
      /** Format: uuid */
      menuItemId: string;
      /** Format: uuid */
      restaurantId: string;
      name: string;
      price: number;
      /** @default EUR */
      currency: string;
      /** @default 1 */
      quantity: number;
    };
    UpdateItemQuantityDto: {
      /** Format: uuid */
      menuItemId: string;
      quantity: number;
    };
    RemoveItemFromCartDto: {
      /** Format: uuid */
      menuItemId: string;
    };
    CheckoutCartDto: {
      deliveryAddress: {
        street: string;
        city: string;
        postalCode: string;
        country: string;
        latitude?: number;
        longitude?: number;
        instructions?: string;
      };
      /** @default 0 */
      deliveryFee: number;
    };
    CreateOrderDto: {
      /** Format: uuid */
      restaurantId: string;
      items: {
        /** Format: uuid */
        menuItemId: string;
        name: string;
        price: number;
        quantity: number;
        /** @default EUR */
        currency: string;
      }[];
      deliveryAddress: {
        street: string;
        city: string;
        postalCode: string;
        country: string;
        latitude?: number;
        longitude?: number;
        instructions?: string;
      };
      /** @default 0 */
      deliveryFee: number;
      /** @default EUR */
      currency: string;
    };
    OrderItemDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      menuItemId: string;
      /** @example Margherita Pizza */
      name: string;
      /** @example 12.99 */
      price: number;
      /** @example EUR */
      currency: string;
      /** @example 2 */
      quantity: number;
    };
    DeliveryAddressDto: {
      /** @example 123 Main Street */
      street: string;
      /** @example New York */
      city: string;
      /** @example 10001 */
      postalCode: string;
      /** @example USA */
      country: string;
    };
    OrderResponseDto: {
      /** @example 123e4567-e89b-12d3-a456-426614174000 */
      id: string;
      /** @example 123e4567-e89b-12d3-a456-426614174001 */
      customerId: string;
      /** @example 123e4567-e89b-12d3-a456-426614174002 */
      restaurantId: string;
      /** @example 123e4567-e89b-12d3-a456-426614174003 */
      driverId?: Record<string, never>;
      items: components["schemas"]["OrderItemDto"][];
      deliveryAddress: components["schemas"]["DeliveryAddressDto"];
      /**
       * @example pending
       * @enum {string}
       */
      status:
        | "pending"
        | "payment_succeeded"
        | "confirmed"
        | "preparing"
        | "ready_for_pickup"
        | "in_transit"
        | "delivered"
        | "cancelled";
      /** @example 25.98 */
      totalAmount: number;
      /** @example 5 */
      deliveryFee: number;
      /** @example EUR */
      currency: string;
      /** @example 2024-01-01T01:00:00.000Z */
      estimatedDeliveryTime?: Record<string, never>;
      /** @example 2024-01-01T01:15:00.000Z */
      actualDeliveryTime?: Record<string, never>;
      /** @example 2024-01-01T00:30:00.000Z */
      cancelledAt?: Record<string, never>;
      /** @example Customer requested cancellation */
      cancellationReason?: Record<string, never>;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    AcceptOrderDto: {
      /** @default 30 */
      estimatedMinutes: number;
    };
    UpdateOrderStatusDto: {
      /** @enum {string} */
      status:
        | "pending"
        | "payment_succeeded"
        | "confirmed"
        | "preparing"
        | "ready_for_pickup"
        | "in_transit"
        | "delivered"
        | "cancelled";
    };
    CancelOrderDto: {
      reason: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      /** @description User registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenDto"];
      };
    };
    responses: {
      /** @description Token refreshed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      /** @description Invalid refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoResponseDto"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_updateUserRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRoleDto"];
      };
    };
    responses: {
      /** @description Role updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all customers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"][];
        };
      };
    };
  };
  CustomersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCustomerDto"];
      };
    };
    responses: {
      /** @description Customer created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"];
        };
      };
    };
  };
  CustomersController_getMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"];
        };
      };
    };
  };
  CustomersController_updateMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCustomerDto"];
      };
    };
    responses: {
      /** @description Profile updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"];
        };
      };
    };
  };
  CustomersController_findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"];
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCustomerDto"];
      };
    };
    responses: {
      /** @description Customer updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponseDto"];
        };
      };
    };
  };
  CustomersController_addAddress: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddAddressDto"];
      };
    };
    responses: {
      /** @description Address added */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_removeAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        addressId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Address removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_addFavorite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Added to favorites */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_removeFavorite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed from favorites */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CustomersController_getFavorites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of favorite restaurants */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of active restaurants */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponseDto"][];
        };
      };
    };
  };
  RestaurantsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRestaurantDto"];
      };
    };
    responses: {
      /** @description Restaurant created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_findAllIncludingInactive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all restaurants */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponseDto"][];
        };
      };
    };
  };
  RestaurantsController_findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restaurant details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponseDto"];
        };
      };
      /** @description Restaurant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRestaurantDto"];
      };
    };
    responses: {
      /** @description Restaurant updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restaurant activated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Restaurant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restaurant deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Restaurant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_confirmOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
        orderId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmOrderDto"];
      };
    };
    responses: {
      /** @description Order confirmed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Restaurant is not active */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Restaurant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RestaurantsController_rejectOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
        orderId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectOrderDto"];
      };
    };
    responses: {
      /** @description Order rejected */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Restaurant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MenuItemsController_findByRestaurant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of menu items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MenuItemResponseDto"][];
        };
      };
    };
  };
  MenuItemsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMenuItemDto"];
      };
    };
    responses: {
      /** @description Menu item created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MenuItemResponseDto"];
        };
      };
    };
  };
  MenuItemsController_findAllByRestaurant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all menu items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MenuItemResponseDto"][];
        };
      };
    };
  };
  MenuItemsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMenuItemDto"];
      };
    };
    responses: {
      /** @description Menu item updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MenuItemResponseDto"];
        };
      };
    };
  };
  MenuItemsController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Menu item deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all drivers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DriverResponseDto"][];
        };
      };
    };
  };
  DriversController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDriverDto"];
      };
    };
    responses: {
      /** @description Driver created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_findAvailable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of available drivers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DriverResponseDto"][];
        };
      };
    };
  };
  DriversController_getMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Driver profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DriverResponseDto"];
        };
      };
    };
  };
  DriversController_updateMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDriverDto"];
      };
    };
    responses: {
      /** @description Profile updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Driver details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DriverResponseDto"];
        };
      };
    };
  };
  DriversController_updateLocation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateLocationDto"];
      };
    };
    responses: {
      /** @description Location updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_setAvailability: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetAvailabilityDto"];
      };
    };
    responses: {
      /** @description Availability updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_deactivateMyAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Driver deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DriversController_deactivateDriver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Driver deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CartsController_getMyCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cart details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartResponseDto"];
        };
      };
    };
  };
  CartsController_clearCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cart cleared */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CartsController_addItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddItemToCartDto"];
      };
    };
    responses: {
      /** @description Item added to cart */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CartsController_removeItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveItemFromCartDto"];
      };
    };
    responses: {
      /** @description Item removed from cart */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CartsController_updateItemQuantity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemQuantityDto"];
      };
    };
    responses: {
      /** @description Item quantity updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CartsController_checkout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutCartDto"];
      };
    };
    responses: {
      /** @description Order created from cart */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cart is empty */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cart not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_createOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderDto"];
      };
    };
    responses: {
      /** @description Order created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_getMyOrders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of customer orders */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderResponseDto"][];
        };
      };
    };
  };
  OrdersController_payForOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payment request initiated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Payment request failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_getAvailableOrders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of available orders */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderResponseDto"][];
        };
      };
    };
  };
  OrdersController_getMyDeliveries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of driver deliveries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderResponseDto"][];
        };
      };
    };
  };
  OrdersController_acceptOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptOrderDto"];
      };
    };
    responses: {
      /** @description Order accepted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_updateOrderStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderStatusDto"];
      };
    };
    responses: {
      /** @description Order status updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_cancelOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelOrderDto"];
      };
    };
    responses: {
      /** @description Order cancelled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrdersController_getOrderById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Order details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderResponseDto"];
        };
      };
    };
  };
}
